### ISSUE TITLE
Рекомендация

### ISSUE THREAD

**Issue by paladyumm** [1050TIt0p/tiDiscordReports#1]
(Это сообщение переведено с другого языка)

Привет, мы недавно установили ваш плагин TiDiscordReports и нам он очень понравился. У нас возникла небольшая проблема: игроки могут спамить командой /report. Могли бы вы добавить в конфигурацию опцию задержки, чтобы предотвратить это?

**Comment by 1050TIt0p** [comment]
https://github.com/1050TIt0p/tiDiscordReports/releases/tag/1.1
